### ISSUE TITLE
console warn - newest 1.3.11 version

### ISSUE THREAD

**Issue by homerek111** [AdvancedPlugins/Seasons#130]
### Describe the bug

[01:24:17 WARN]: [AdvancedSeasons] Plugin AdvancedSeasons v1.3.11 generated an exception while executing task 49355
java.lang.IllegalArgumentException: y out of range (expected -64-320, got 406)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunk.validateChunkCoordinates(CraftChunk.java:424) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunkSnapshot.validateChunkCoordinates(CraftChunkSnapshot.java:188) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunkSnapshot.getBlockType(CraftChunkSnapshot.java:100) ~[paper-1.20.4.jar:git-Paper-496]
        at net.advancedplugins.seasons.visuals.type.AbstractFallingLeafVisual.createFallingSnowFromLeaves(AbstractFallingLeafVisual.java:77) ~[AdvancedSeasons-1.3.11.jar:?]
        at net.advancedplugins.seasons.visuals.type.AbstractFallingLeafVisual.tick(AbstractFallingLeafVisual.java:22) ~[AdvancedSeasons-1.3.11.jar:?]
        at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
        at net.advancedplugins.seasons.visuals.VisualsHandler.lambda$new$0(VisualsHandler.java:28) ~[AdvancedSeasons-1.3.11.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[01:24:17 WARN]: [AdvancedSeasons] Plugin AdvancedSeasons v1.3.11 generated an exception while executing task 49355
java.lang.IllegalArgumentException: y out of range (expected -64-320, got 392)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunk.validateChunkCoordinates(CraftChunk.java:424) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunkSnapshot.validateChunkCoordinates(CraftChunkSnapshot.java:188) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunkSnapshot.getBlockType(CraftChunkSnapshot.java:100) ~[paper-1.20.4.jar:git-Paper-496]
        at net.advancedplugins.seasons.visuals.type.AbstractFallingLeafVisual.createFallingSnowFromLeaves(AbstractFallingLeafVisual.java:77) ~[AdvancedSeasons-1.3.11.jar:?]
        at net.advancedplugins.seasons.visuals.type.AbstractFallingLeafVisual.tick(AbstractFallingLeafVisual.java:22) ~[AdvancedSeasons-1.3.11.jar:?]
        at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
        at net.advancedplugins.seasons.visuals.VisualsHandler.lambda$new$0(VisualsHandler.java:28) ~[AdvancedSeasons-1.3.11.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[01:24:18 WARN]: [AdvancedSeasons] Plugin AdvancedSeasons v1.3.11 generated an exception while executing task 49355
java.lang.IllegalArgumentException: y out of range (expected -64-320, got 376)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunk.validateChunkCoordinates(CraftChunk.java:424) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunkSnapshot.validateChunkCoordinates(CraftChunkSnapshot.java:188) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunkSnapshot.getBlockType(CraftChunkSnapshot.java:100) ~[paper-1.20.4.jar:git-Paper-496]
        at net.advancedplugins.seasons.visuals.type.AbstractFallingLeafVisual.createFallingSnowFromLeaves(AbstractFallingLeafVisual.java:77) ~[AdvancedSeasons-1.3.11.jar:?]
        at net.advancedplugins.seasons.visuals.type.AbstractFallingLeafVisual.tick(AbstractFallingLeafVisual.java:22) ~[AdvancedSeasons-1.3.11.jar:?]
        at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
        at net.advancedplugins.seasons.visuals.VisualsHandler.lambda$new$0(VisualsHandler.java:28) ~[AdvancedSeasons-1.3.11.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[01:24:18 WARN]: [AdvancedSeasons] Plugin AdvancedSeasons v1.3.11 generated an exception while executing task 49355
java.lang.IllegalArgumentException: y out of range (expected -64-320, got 355)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunk.validateChunkCoordinates(CraftChunk.java:424) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunkSnapshot.validateChunkCoordinates(CraftChunkSnapshot.java:188) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunkSnapshot.getBlockType(CraftChunkSnapshot.java:100) ~[paper-1.20.4.jar:git-Paper-496]
        at net.advancedplugins.seasons.visuals.type.AbstractFallingLeafVisual.createFallingSnowFromLeaves(AbstractFallingLeafVisual.java:77) ~[AdvancedSeasons-1.3.11.jar:?]
        at net.advancedplugins.seasons.visuals.type.AbstractFallingLeafVisual.tick(AbstractFallingLeafVisual.java:22) ~[AdvancedSeasons-1.3.11.jar:?]
        at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
        at net.advancedplugins.seasons.visuals.VisualsHandler.lambda$new$0(VisualsHandler.java:28) ~[AdvancedSeasons-1.3.11.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[01:24:19 WARN]: [AdvancedSeasons] Plugin AdvancedSeasons v1.3.11 generated an exception while executing task 49355
java.lang.IllegalArgumentException: y out of range (expected -64-320, got 331)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunk.validateChunkCoordinates(CraftChunk.java:424) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunkSnapshot.validateChunkCoordinates(CraftChunkSnapshot.java:188) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftChunkSnapshot.getBlockType(CraftChunkSnapshot.java:100) ~[paper-1.20.4.jar:git-Paper-496]
        at net.advancedplugins.seasons.visuals.type.AbstractFallingLeafVisual.createFallingSnowFromLeaves(AbstractFallingLeafVisual.java:77) ~[AdvancedSeasons-1.3.11.jar:?]
        at net.advancedplugins.seasons.visuals.type.AbstractFallingLeafVisual.tick(AbstractFallingLeafVisual.java:22) ~[AdvancedSeasons-1.3.11.jar:?]
        at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
        at net.advancedplugins.seasons.visuals.VisualsHandler.lambda$new$0(VisualsHandler.java:28) ~[AdvancedSeasons-1.3.11.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### How to reproduce

idk what happened - it just spammed my console

**Comment by kubiiikk** [comment]
The same thing happens to me, if the player flies with the elytra above the height limit of 320, it starts spamming this error
(Version: 1.3.9)

**Comment by GC-spigot** [comment]
Fixed!
