### ISSUE TITLE
I get this error whenever I want to update the plugin

### ISSUE THREAD

**Issue by AronV4** [AdvancedPlugins/Seasons#131]
### Describe the bug

I get this error whenever I want to update the plugin
ARCLIGHT 1.20.1

### How to reproduce

I want to update the plugin. But I always get this error and the plugin does not work.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/691a692b-6856-47df-81e9-ce9379c0a7ae)

**Comment by GC-spigot** [comment]
We're unsure why the error happens, seems to be doing with some invalid biome, this *should* be solved next update. Let us know if it is.

**Comment by AronV4** [comment]
<img width="548" alt="Captura de pantalla 2024-07-26 141550" src="https://github.com/user-attachments/assets/71006fac-fcfd-47b9-acbf-d321550b8efc">

I think it works now. This keeps popping up. But it is no longer in red and I can use the commands

**Comment by AronV4** [comment]
with the latest update. The plugin loads correctly but when I use the /seasons add world world command, I get a red error.



ERROR:
[22:02:45 INFO]: AronV4 issued server command: /seasons addworld world
[22:02:45 ERROR] [Minecraft]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'seasons' in plugin AdvancedSeasons v1.4.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23290!/:arclight-1.20.1-1.0.5-1a8925b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23290!/:arclight-1.20.1-1.0.5-1a8925b]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServerMixin.java:877) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23290!/:arclight-1.20.1-1.0.5-1a8925b]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23290!/:arclight-1.20.1-1.0.5-1a8925b]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar%23110!/:?]
        at net.minecraft.commands.Commands.m_242674_(CommandsMixin.java:257) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerPlayNetHandlerMixin.java:2853) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_244885_(ServerPlayNetHandlerMixin.java:1223) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23419!/:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean org.bukkit.persistence.PersistentDataContainer.has(org.bukkit.NamespacedKey)'
        at net.advancedplugins.seasons.persistent.NBTValueResolver.isPresent(NBTValueResolver.java:51) ~[?:?]
        at net.advancedplugins.seasons.persistent.calendar.WorldCalendarDataReader.selectReader(WorldCalendarDataReader.java:29) ~[?:?]
        at net.advancedplugins.seasons.calendar.CalendarFactory.loadCalendar(CalendarFactory.java:21) ~[?:?]
        at net.advancedplugins.seasons.world.WorldHandlerImpl.loadWorld(WorldHandlerImpl.java:149) ~[?:?]
        at net.advancedplugins.seasons.world.WorldHandlerImpl.hookInto0(WorldHandlerImpl.java:89) ~[?:?]
        at net.advancedplugins.seasons.world.WorldHandlerImpl.hookInto(WorldHandlerImpl.java:85) ~[?:?]
        at net.advancedplugins.seasons.handlers.WorldHandler.addWorld(WorldHandler.java:22) ~[?:?]
        at net.advancedplugins.seasons.commands.sub.AddWorldSub.onExecute(AddWorldSub.java:29) ~[?:?]
        at net.advancedplugins.as.impl.utils.commands.Command.middleMan(Command.java:28) ~[?:?]
        at net.advancedplugins.as.impl.utils.commands.CommandBase.onCommand(CommandBase.java:98) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23290!/:arclight-1.20.1-1.0.5-1a8925b]
        ... 22 more

**Comment by AronV4** [comment]
also on their website
https://advancedplugins.net/

is it possible to enable an option to download older versions?
