### ISSUE TITLE
How to stop adding new short grass in spring?

### ISSUE THREAD

**Issue by tsingyayin** [AdvancedPlugins/Seasons#139]
### Describe the bug

My server players complained to me that they got too many short grass. However, I noticed that in blocks.yml, I have set the `generateCustomGrass` of the corresponding world to `false`. It seems that the configuration does not work.

I can confirm that the world name is correct.

I remember this problem occurred in the plugin from the day I bought it (about 4 months ago).

### How to reproduce

1. Open `blocks.yml`
2. Set `worlds.world.generateCustomGrass` to `false`
3. Spring will still have short grass to be generated.

### Screenshots / Videos

There is nothing to show except the short grass everywhere

**Comment by Ynverxe** [comment]
Photos?

**Comment by tsingyayin** [comment]
![2024-08-15_21 27 16](https://github.com/user-attachments/assets/cd3abb65-275d-4fb7-85d5-883c401e4a67)
Short grass everywhere

**Comment by Ynverxe** [comment]
Thank you! So I'll need more information. Please provide me your AS configuration files and the latest log of your server(serverDir/logs/latest.log).

**Comment by tsingyayin** [comment]
[AdvancedSeasons.zip](https://github.com/user-attachments/files/16627944/AdvancedSeasons.zip)
I'm very sorry, because our server logs also record the chats on our external community platform, they can't be pushed to the public until I handle them. If you have to, I will try my best to write a small script to handle it within 24 hours and send it here

**Comment by tsingyayin** [comment]
Plugin version 1.3.14, and just as what I have pointted, it has occurred at least 4 months

**Comment by tsingyayin** [comment]
Personally, I don't think it's worth noticing. At least as far as today's log is concerned, I only saw a log of SpigotLibLoader after starting the server.

However, it should be noted that AdvancedSeasons does occasionally destroy my MSPT recently, and then I usually receive such Exception reports:
```plain
[23:02:57] [Craft Scheduler Thread - 10193 - AdvancedSeasons/WARN]: [AdvancedSeasons] Plugin AdvancedSeasons v1.3.14 generated an exception while executing task 464
java.lang.IllegalArgumentException: y out of range (expected -64-320, got -69)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.CraftChunk.validateChunkCoordinates(CraftChunk.java:432) ~[purpur-1.21.jar:1.21-2280-930003b]
	at org.bukkit.craftbukkit.CraftChunkSnapshot.validateChunkCoordinates(CraftChunkSnapshot.java:188) ~[purpur-1.21.jar:1.21-2280-930003b]
	at org.bukkit.craftbukkit.CraftChunkSnapshot.getBlockType(CraftChunkSnapshot.java:100) ~[purpur-1.21.jar:1.21-2280-930003b]
	at AdvancedSeasons-1.3.14.jar/net.advancedplugins.seasons.visuals.type.AbstractFallingLeafVisual.createFallingSnowFromLeaves(AbstractFallingLeafVisual.java:80) ~[AdvancedSeasons-1.3.14.jar:?]
	at AdvancedSeasons-1.3.14.jar/net.advancedplugins.seasons.visuals.type.AbstractFallingLeafVisual.tick(AbstractFallingLeafVisual.java:22) ~[AdvancedSeasons-1.3.14.jar:?]
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1016) ~[?:?]
	at AdvancedSeasons-1.3.14.jar/net.advancedplugins.seasons.visuals.VisualsHandler.lambda$new$0(VisualsHandler.java:28) ~[AdvancedSeasons-1.3.14.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2280-930003b]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.jar:1.21-2280-930003b]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
Once such reports appear, they usually appear hundreds of times in succession：
![image](https://github.com/user-attachments/assets/0f23ff08-e19f-4635-971d-671f116fdd79)
![image](https://github.com/user-attachments/assets/5656542f-4388-45fc-823d-58b928b2c1a5)
**Pay attention to the line number on the left. It's really crazy**

**Comment by tsingyayin** [comment]
So what progress has been made in the generation of short grass?

**Comment by Ynverxe** [comment]
> So what's new about the bug of short grass

I'm still working on that.

**Comment by Ynverxe** [comment]
Seems that the grass accumulation is caused when winter changes to spring.

When this happens AS generates grass in places where there is snow. When this happens many times, the number of grass is increasing.

**Comment by tsingyayin** [comment]
Is there any plan to further promote or completely solve this issue in the near future ? (before the end of the year)
