### ISSUE TITLE
SPAMMING WARNING MESSAGE

### ISSUE THREAD

**Issue by kooyhee** [AdvancedPlugins/Seasons#155]
### Describe the bug

[15:22:31 WARN]: java.lang.NoSuchFieldException: c
[15:22:31 WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2782)
[15:22:31 WARN]: 	at AdvancedSeasons-1.4.9.jar//net.advancedplugins.seasons.biomes.nms.NMSBiome_1_20_3.sendChunkUpdate(NMSBiome_1_20_3.java:170)
[15:22:31 WARN]: 	at AdvancedSeasons-1.4.9.jar//net.advancedplugins.seasons.handlers.RenderHandler.processChunkUpdates(RenderHandler.java:88)
[15:22:31 WARN]: 	at AdvancedSeasons-1.4.9.jar//net.advancedplugins.seasons.handlers.RenderHandler.lambda$new$0(RenderHandler.java:36)
[15:22:31 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[15:22:31 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[15:22:31 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1688)
[15:22:31 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:492)
[15:22:31 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1567)
[15:22:31 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1249)
[15:22:31 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[15:22:31 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

### How to reproduce

SPAMMING WARNING MESSAGE IN CONSOLE
HOW TO SOLVE THIS PROBLEM?

**Comment by GC-spigot** [comment]
Hi! Thanks for the report, we’ll look into it! On 9 Sep 2024, at 9:28 AM, kooyhee ***@***.***> wrote:﻿
Describe the bug
[15:22:31 WARN]: java.lang.NoSuchFieldException: c
[15:22:31 WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2782)
[15:22:31 WARN]: 	at AdvancedSeasons-1.4.9.jar//net.advancedplugins.seasons.biomes.nms.NMSBiome_1_20_3.sendChunkUpdate(NMSBiome_1_20_3.java:170)
[15:22:31 WARN]: 	at AdvancedSeasons-1.4.9.jar//net.advancedplugins.seasons.handlers.RenderHandler.processChunkUpdates(RenderHandler.java:88)
[15:22:31 WARN]: 	at AdvancedSeasons-1.4.9.jar//net.advancedplugins.seasons.handlers.RenderHandler.lambda$new$0(RenderHandler.java:36)
[15:22:31 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[15:22:31 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[15:22:31 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1688)
[15:22:31 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:492)
[15:22:31 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1567)
[15:22:31 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1249)
[15:22:31 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[15:22:31 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
How to reproduce
SPAMMING WARNING MESSAGE IN CONSOLE
HOW TO SOLVE THIS PROBLEM?
Screenshots / Videos
No response
Server Log
No response

**Comment by Ynverxe** [comment]
Which server type are you using?
