### ISSUE TITLE
Temperature error

### ISSUE THREAD

**Issue by EagL3-GIT** [AdvancedPlugins/Seasons#162]
### Describe the bug

[13:44:59 ERROR]: Could not pass event EntityDamageEvent to AdvancedSeasons v1.4.13
java.lang.NullPointerException: Cannot invoke "net.advancedplugins.seasons.temperature.TemperatureHandler.getAbilities()" because the return value of "net.advancedplugins.seasons.Core.getTemperatureHandler()" is null
at net.advancedplugins.seasons.Core.lambda$registerAbilities$0(Core.java:293) ~[AdvancedSeasons-1.4.13.jar:?]
at net.advancedplugins.as.impl.effects.effects.actions.ActionExecutionBuilder.build(ActionExecutionBuilder.java:91) ~[AdvancedSeasons-1.4.13.jar:?]
at net.advancedplugins.as.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:73) ~[AdvancedSeasons-1.4.13.jar:?]
at net.advancedplugins.as.impl.effects.effects.mechanics.triggers.internal.ElytraFlyDamageTrigger.onDamage(ElytraFlyDamageTrigger.java:36) ~[AdvancedSeasons-1.4.13.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1439.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-497]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-497]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-497]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:267) ~[paper-1.20.4.jar:git-Paper-497]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1203) ~[paper-1.20.4.jar:git-Paper-497]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1188) ~[paper-1.20.4.jar:git-Paper-497]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1178) ~[paper-1.20.4.jar:git-Paper-497]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1081) ~[paper-1.20.4.jar:git-Paper-497]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1237) ~[paper-1.20.4.jar:git-Paper-497]
at net.minecraft.world.entity.LivingEntity.actuallyHurt(LivingEntity.java:2243) ~[?:?]
at net.minecraft.world.entity.player.Player.actuallyHurt(Player.java:1063) ~[?:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1480) ~[?:?]
at net.minecraft.world.entity.player.Player.hurt(Player.java:970) ~[?:?]
at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1135) ~[?:?]
at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2879) ~[?:?]
at net.minecraft.world.entity.player.Player.travel(Player.java:1682) ~[?:?]
at net.minecraft.server.level.ServerPlayer.travel(ServerPlayer.java:1726) ~[?:?]
at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3474) ~[?:?]
at net.minecraft.world.entity.player.Player.aiStep(Player.java:570) ~[?:?]
at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3066) ~[?:?]
at net.minecraft.world.entity.player.Player.tick(Player.java:274) ~[?:?]
at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:770) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:338) ~[?:?]
at net.minecraft.network.Connection.tick(Connection.java:593) ~[?:?]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1746) ~[paper-1.20.4.jar:git-Paper-497]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-497]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-497]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-497]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to reproduce

Start the server with newest version of advanced seasons and check console..

**Comment by Ynverxe** [comment]
That's weird. Can you provide us your server log where this error shows?
