### ISSUE TITLE
Error while reloading the plugin

### ISSUE THREAD

**Issue by EagL3-GIT** [AdvancedPlugins/Seasons#33]
### Describe the bug

Error while using plugin reload.

### How to reproduce

[14:35:39 INFO]: _EagL3 issued server command: /advancedseasons reload
[14:35:39 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'advancedseasons' in plugin AdvancedSeasons v1.0.18
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.4.jar:git-Paper-364]
at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-364]
at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[paper-1.20.4.jar:git-Paper-364]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-364]
at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-364]
at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-364]
at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[paper-1.20.4.jar:git-Paper-364]
at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:444) ~[?:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[?:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2234) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2194) ~[?:?]
at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-364]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-364]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-364]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-364]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-364]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-364]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-364]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-364]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitTask.getTaskId()" because "this.locationScanner" is null
at net.advancedplugins.seasons.handlers.sub.BlockProcessHandler.stopTasks(BlockProcessHandler.java:378) ~[AdvancedSeasons-1.0.19.jar:?]
at net.advancedplugins.seasons.Core.unload(Core.java:371) ~[AdvancedSeasons-1.0.19.jar:?]
at net.advancedplugins.seasons.Core.init(Core.java:314) ~[AdvancedSeasons-1.0.19.jar:?]
at net.advancedplugins.seasons.commands.sub.ReloadSub.onExecute(ReloadSub.java:23) ~[AdvancedSeasons-1.0.19.jar:?]
at net.advancedplugins.as.impl.utils.commands.Command.middleMan(Command.java:28) ~[AdvancedSeasons-1.0.19.jar:?]
at net.advancedplugins.as.impl.utils.commands.CommandBase.onCommand(CommandBase.java:97) ~[AdvancedSeasons-1.0.19.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
... 29 more

**Comment by EagL3-GIT** [comment]
@GC-spigot

**Comment by GC-spigot** [comment]
Thank you fixed
