### ISSUE TITLE
It doesnt snow or rain on my Server.

### ISSUE THREAD

**Issue by 1Wolke** [AdvancedPlugins/Seasons#36]
### Describe the bug

I loaded the plugin onto my 1.20.1 spigot server yesterday and everything seemed to work at first. The biomes change colors and the temperature affects the player. However, I then noticed that it wasn't snowing or raining anymore. The water doesn't freeze in winter and the normal /weather command doesn't work either.

### How to reproduce

Spigot 1.20.1 / Plugins : dynmap, voicechat, WorldEdit, Tamablefoxes, DiscordSRV, ChunkLoader, AFKPlus, ProtectedZones, GSit, TabTPS, ProtocolLib, Images, sleep-most, AdvancedSeasons

### Screenshots / Videos

![2024-02-11_13 02 03](https://github.com/AdvancedPlugins/Seasons/assets/159696263/6cebe62a-0244-4862-b75e-c10fb5f50e3e)
![2024-02-11_13 02 42](https://github.com/AdvancedPlugins/Seasons/assets/159696263/a353b43d-0516-4fdd-b8cc-9f3fdc3819c4)

### Server Log
- [Sun 13:42:57 ERROR Minecraft] Could not pass event CreatureSpawnEvent to AdvancedSeasons v1.1.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:717)
    at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:636)
    at net.minecraft.server.level.WorldServer.addEntity(WorldServer.java:1080)
    at net.minecraft.server.level.WorldServer.addFreshEntity(WorldServer.java:1017)
    at net.minecraft.world.level.WorldAccess.lambda$0(WorldAccess.java:16)
    at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
    at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
    at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
    at net.minecraft.world.level.WorldAccess.addFreshEntityWithPassengers(WorldAccess.java:16)
    at net.minecraft.world.level.SpawnerCreature.a(SpawnerCreature.java:230)
    at net.minecraft.world.level.SpawnerCreature.a(SpawnerCreature.java:159)
    at net.minecraft.world.level.SpawnerCreature.a(SpawnerCreature.java:147)
    at net.minecraft.server.level.ChunkProviderServer.t(ChunkProviderServer.java:447)
    at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:387)
    at net.minecraft.server.level.WorldServer.a(WorldServer.java:399)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1302)
    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198)
    at net.minecraft.server.MinecraftS

**Comment by PresidentEvil21** [comment]
running 1.20.1  spigot server too and have the same behaviour, weather does not change and no ice

**Comment by 1Wolke** [comment]
I fixed it by simply installing on Paper. All my plugins still work and now the weather works too. I also tried with another server, the problem seems to be with Spigot (1.20.1). The other plugins don't cause any problems for me.

**Comment by PresidentEvil21** [comment]
Okay ill try out thanks!

**Comment by PresidentEvil21** [comment]
[before] 
https://prnt.sc/YlmhR6ixnU1B'
https://prnt.sc/i21tzXzrm70x
[after updating to paper]
https://prnt.sc/8o15ghVGc9VP
