### ISSUE TITLE
Could not pass event CreatureSpawnEvent to AdvancedSeasons v1.2.6

### ISSUE THREAD

**Issue by Pilvinen** [AdvancedPlugins/Seasons#89]
### Describe the bug

Spigot running Minecraft 1.20.6
ProtocolLib dev build #689 (May 6, 2024, 5:02:54 PM)
WorldGuard version/7.0.x	[#2267]

I'm seeing this error on the console:

[19:27:03] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to AdvancedSeasons v1.2.6
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:600) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:587) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R4.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:749) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at org.bukkit.craftbukkit.v1_20_R4.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:668) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.server.level.WorldServer.addEntity(WorldServer.java:1103) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.server.level.WorldServer.addFreshEntity(WorldServer.java:1040) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.world.level.WorldAccess.lambda$addFreshEntityWithPassengers$0(WorldAccess.java:16) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:782) ~[?:?]
at net.minecraft.world.level.WorldAccess.addFreshEntityWithPassengers(WorldAccess.java:16) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.world.level.SpawnerCreature.a(SpawnerCreature.java:225) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.world.level.SpawnerCreature.a(SpawnerCreature.java:154) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.world.level.SpawnerCreature.a(SpawnerCreature.java:142) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.server.level.ChunkProviderServer.t(ChunkProviderServer.java:433) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:375) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.server.level.WorldServer.a(WorldServer.java:411) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1444) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:402) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1293) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1064) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.entity.Entity org.bukkit.World.spawnEntity(org.bukkit.Location, org.bukkit.entity.EntityType, org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason)'
at net.advancedplugins.seasons.handlers.SeasonalMobsHandler.onMobSpawn(SeasonalMobsHandler.java:109) ~[?:?]
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
... 24 more

### How to reproduce

It just pops up, apparently when AdvancedSeasons tries to spawn something.

**Comment by Pilvinen** [comment]
Seems to have been fixed by AdvancedSeasons v1.2.7.
