### ISSUE TITLE
placeholder not working

### ISSUE THREAD

**Issue by efor89** [AdvancedPlugins/Seasons#97]
### Describe the bug

i try the 2 new placholder but the only show "Spring", in each season.
%advancedseasons_season_next%
%advancedseasons_season_remainingdays%

### How to reproduce

1. use TAB for scoreboard
2. set in scoreboard the placeholder
3. start server and join 
4. placeholder = Spring

### Screenshots / Videos

![Screenshot (321)](https://github.com/AdvancedPlugins/Seasons/assets/67799203/5f280267-e118-40e2-8ea3-421d19beee39)

**Comment by efor89** [comment]
screenshot in season fall
![Screenshot (322)](https://github.com/AdvancedPlugins/Seasons/assets/67799203/8f060a4b-149f-4f78-8728-5e3bce0b194f)

**Comment by Ynverxe** [comment]
Fixed.

**Comment by efor89** [comment]
and what is this?

[18:25:35 WARN]: java.lang.NoSuchFieldException: c
[18:25:35 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2792)
[18:25:35 WARN]:        at AdvancedSeasons-1.3.2.jar//net.advancedplugins.seasons.biomes.nms.NMSBiome_1_20_3.sendChunkUpdate(NMSBiome_1_20_3.java:159)
[18:25:35 WARN]:        at AdvancedSeasons-1.3.2.jar//net.advancedplugins.seasons.handlers.RenderHandler.processChunkUpdates(RenderHandler.java:88)
[18:25:35 WARN]:        at AdvancedSeasons-1.3.2.jar//net.advancedplugins.seasons.handlers.RenderHandler.lambda$new$0(RenderHandler.java:36)
[18:25:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[18:25:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[18:25:35 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1639)
[18:25:35 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[18:25:35 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1518)
[18:25:35 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1214)
[18:25:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[18:25:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[18:25:35 WARN]: java.lang.NoSuchFieldException: c
[18:25:35 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2792)
[18:25:35 WARN]:        at AdvancedSeasons-1.3.2.jar//net.advancedplugins.seasons.biomes.nms.NMSBiome_1_20_3.sendChunkUpdate(NMSBiome_1_20_3.java:159)
[18:25:35 WARN]:        at AdvancedSeasons-1.3.2.jar//net.advancedplugins.seasons.handlers.RenderHandler.processChunkUpdates(RenderHandler.java:88)
[18:25:35 WARN]:        at AdvancedSeasons-1.3.2.jar//net.advancedplugins.seasons.handlers.RenderHandler.lambda$new$0(RenderHandler.java:36)
[18:25:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[18:25:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[18:25:35 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1639)
[18:25:35 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[18:25:35 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1518)
[18:25:35 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1214)
[18:25:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[18:25:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by efor89** [comment]
@Ynverxe
